#################################
##            Home             ##
#################################

homepage:
    path:     /
    defaults: {_controller: AppBundle:User:homepage }

#################################
##            AJAX             ##
#################################

ajax_photos:
    path:     /ajax/photos
    defaults: {_controller: AppBundle:Photo:getPhotoPaths }

ajax_latlon:
    path:     /ajax/latlon
    defaults: {_controller: AppBundle:Photo:getLatLons }

ajax_photo:
    path:     /ajax/photo/{id}
    defaults: {_controller: AppBundle:Photo:getArt }



#################################
##            Security         ##
#################################

login:
    path:     /login
    defaults: {_controller: AppBundle:Security:login }

login_check:
    path:     /login_check
    defaults: {_controller: AppBundle:Security:loginCheck }

logout:
    path:     /logout


#################################
##        	  Users  	       ##
#################################

user:
    path:     /admin/users
    defaults: {_controller: AppBundle:User:index }

user_new:
    path:   /user/new
    defaults: { _controller: AppBundle:User:new }

user_create:
    path:   /user/create
    defaults: { _controller: AppBundle:User:create }

user_edit:
    path:   /user/edit/{id}
    defaults: {_controller: AppBundle:User:edit }

user_update:
    path:   /user/update/{id}
    defaults: {_controller: AppBundle:User:update }

user_delete:
    path:   /user/delete/{id}
    defaults: {_controller: AppBundle:User:delete }

user_show:
    path:   /user/{id}
    defaults: {_controller: AppBundle:User:show }

#################################
##            tags            ##
#################################

tag:
    path:     /admin/tags
    defaults: {_controller: AppBundle:Tag:index }

tag_new:
    path:   /admin/tag/new
    defaults: { _controller: AppBundle:Tag:new }

tag_create:
    path:   /admin/tag/create
    defaults: { _controller: AppBundle:Tag:create }

tag_edit:
    path:   /admin/tag/edit/{id}
    defaults: {_controller: AppBundle:Tag:edit }

tag_update:
    path:   /admin/tag/update/{id}
    defaults: {_controller: AppBundle:Tag:update }

tag_delete:
    path:   /admin/tag/delete/{id}
    defaults: {_controller: AppBundle:Tag:delete }

tag_show:
    path:   /tag/{id}
    defaults: {_controller: AppBundle:Tag:show }

#################################
##            photos           ##
#################################

photo:
    path:     /admin/photos
    defaults: {_controller: AppBundle:Photo:index }

photo_new:
    path:   /photo/new
    defaults: { _controller: AppBundle:Photo:new }

photo_create:
    path:   /photo/create
    defaults: { _controller: AppBundle:Photo:create }

photo_edit:
    path:   /photo/edit/{id}
    defaults: {_controller: AppBundle:Photo:edit }

photo_update:
    path:   /photo/update/{id}
    defaults: {_controller: AppBundle:Photo:update }

photo_delete:
    path:   /photo/delete/{id}
    defaults: {_controller: AppBundle:Photo:delete }

photo_show:
    path:   /photo/{id}
    defaults: {_controller: AppBundle:Photo:show }

upload:
    path:     /upload
    defaults: {_controller: AppBundle:Photo:upload }