#################################
##        	  Users  	       ##
#################################

_users:
    path:     /users
    defaults: {_controller: AppBundle:User:index }

_user_new:
    path:   /user/new
    defaults: { _controller: AppBundle:User:new }

_user_create:
    path:   /user/create
    defaults: { _controller: AppBundle:User:create }

_user_edit:
    path:   /user/edit/{id}
    defaults: {_controller: AppBundle:User:edit }

_user_update:
    path:   /user/update/{id}
    defaults: {_controller: AppBundle:User:update }
    
_user_delete:
    path:   /user/delete/{id}
    defaults: {_controller: AppBundle:User:delete }

_user_show:
    path:   /user/{id}
    defaults: {_controller: AppBundle:User:show }