#################################
##        	  Users  	       ##
#################################

user:
    path:     /users
    defaults: {_controller: AppBundle:User:index }

user_new:
    path:   /user/new
    defaults: { _controller: AppBundle:User:new }

user_create:
    path:   /user/create
    defaults: { _controller: AppBundle:User:create }

user_edit:
    path:   /user/edit/{id}
    defaults: {_controller: AppBundle:User:edit }

user_update:
    path:   /user/update/{id}
    defaults: {_controller: AppBundle:User:update }

user_delete:
    path:   /user/delete/{id}
    defaults: {_controller: AppBundle:User:delete }

user_show:
    path:   /user/{id}
    defaults: {_controller: AppBundle:User:show }