photo:
    path:     /
    defaults: { _controller: "AppBundle:Photo:index" }

photo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Photo:show" }

photo_new:
    path:     /new
    defaults: { _controller: "AppBundle:Photo:new" }

photo_create:
    path:     /create
    defaults: { _controller: "AppBundle:Photo:create" }
    methods:  POST

photo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Photo:edit" }

photo_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Photo:update" }
    methods:  [POST, PUT]

photo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Photo:delete" }
    methods:  [POST, DELETE]
